/*
 * This source file was generated by the Gradle 'init' task
 */
package quiz2;

import quiz2.Util.CLIUtil;
import quiz2.Views.FurniturView;

public class App {
    

    public static void main(String[] args) {
        FurniturView menu = new FurniturView();
        menu.render();
    }
}
