/*
 * This source file was generated by the Gradle 'init' task
 */
package minggu6;

import minggu6.views.MenuView;



public class App {
    public static void main(String[] args) {

        MenuView menuView = new MenuView();
        menuView.render();

        // System.out.println("Hello World!");
        // System.out.println("--------------------------------------------------------");

        // // Data Dummy 
        
        // // Matakuliah
        // MataKuliah pbo = new MataKuliah("IF-301", "Pemrograman Berorientasi Objek", 3);
        // MataKuliah advanceAI = new MataKuliah("IF-1202", "Advance Artificial Intelligence", 3);

        // // Mahasiswa Sarjana
        // MahasiswaSarjana jordan = new MahasiswaSarjana("1124008", "Jordan Alexander Suwito", "Bandung", "12 Juli 2006", "Holis", "08157839275", "IF");
        
        // // Matkul ambil
        // MatKulAmbil mk_pbo = new MatKulAmbil(pbo, 0, 0, 0);

        // //Presensi Mahasiswa
        // Presensi presensi_12_okt_2025 = new Presensi("12 Oktober 2025", 1);
        // mk_pbo.addPresensi(presensi_12_okt_2025);
        // jordan.addMatakuliahDiambil(mk_pbo);
        
        // jordan.getMatakuliahDiambil().get(0).addPresensi(new Presensi("13 Oktober 2025", 1));
        // jordan.getMatakuliahDiambil().get(0).setN1(90);
        // jordan.getMatakuliahDiambil().get(0).setN2(100);
        // jordan.getMatakuliahDiambil().get(0).setN3(56);
        // System.out.println(jordan);
        // System.out.println("--------------------------------------------------------");


        // // Mahasiswa Magister
        // MahasiswaMagister marvel = new MahasiswaMagister("11125001", "Marvel Nathanael Lie", "Bandung", "23 July 2006", "Margaasih", "08123456789", "IF");
        
        // // Matkul ambil
        // MatKulAmbil mk_advanceAI = new MatKulAmbil(advanceAI, 0, 0, 0);

        // // Presensi Mahasiswa
        // Presensi presensi_23_july_2025 = new Presensi("23 July 2025", 1);
        // marvel.addMatakuliahDiambil(mk_advanceAI);
        // mk_advanceAI.addPresensi(presensi_23_july_2025);


        // // Mahasiswa Doctor
        // MahasiswaDoctor leon = new MahasiswaDoctor("1124016", "Leonard Samuel Setiawan", "Bandung", "08 Maret 2005", "Cimahi", "08198765432", "IF", "AI for Healthcare", 0, 50, 0);
        // leon.setJudulDisertasi("Accenture in one API");
        // System.out.println(leon);
        // System.out.println("--------------------------------------------------------");


        // // Karyawan
        // Karyawan kohjia = new Karyawan(10000000);
        // kohjia.addPresensiStaff(new PresensiStaff("12 Oktober 2024", 1, 10));
        // System.out.println(kohjia.getPresensiStaff().get(0).getStatus());

        // // Dosen Tetap
        // DosenTetap ingeMartina = new DosenTetap("90175175842", "Inge Martina", "Surabaya", "23 Januari 2025", "Margahayu", "082365273582", "IF", 12000000);
        // DosenHonorer hans = new DosenHonorer("9017236475842", "Hans", "Jakarta", "11 Januari 2025", "Cicendo", "082365546682", "IF", 1200000);

        // // Matkul ambil
        // MatKulAjar mka_pbo = new MatKulAjar(pbo);
        // ingeMartina.addMatkulAjar(mka_pbo);

        // MatKulAjar mka_advanceAI = new MatKulAjar(advanceAI);
        // hans.addMatkulAjar(mka_advanceAI);
        
        // hans.getMatkulAjar().get(0).addPresensiStaff(new PresensiStaff("12 Mei 2021", 1, 3));
        // System.out.println(hans);
        
    }
}
