/*
 * This source file was generated by the Gradle 'init' task
 */
package pracKuis3;

import java.util.Comparator;

import pracKuis3.models.CustomList;
import pracKuis3.models.NegativeNumberException;
import pracKuis3.views.Menu;

public class App {

    public static void main(String[] args) throws NegativeNumberException {
        CustomList<Integer> myList = new CustomList<>();
        Menu menu = new Menu();
        menu.render();
    }
}
