/*
 * This source file was generated by the Gradle 'init' task
 */
package pertemuan2;

// Library
import java.util.Scanner;

// Repository

import jdk.jshell.EvalException;
import pertemuan2.repository.JurusanRepository;
import pertemuan2.repository.MahasiswaRepository;
import pertemuan2.repository.MataKuliahRepository;
import pertemuan2.repository.EvaluateRepository;

import pertemuan2.models.Jurusan;
import pertemuan2.models.Mahasiswa;
import pertemuan2.models.MataKuliah;

public class App {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        do {
            System.out.println("Pilihan menu:\n1. Jurusan\n2. Matakuliah\n3. Mahasiswa\n4. Menilai Matakuliah\n5. Input IP\n6. Exit\nPilihan(1-6): ");
            int menu_first = Integer.parseInt(sc.nextLine());
            if (menu_first == 1 || menu_first == 2 || menu_first == 3) {
                int sub_menu;
                String result;
                switch (menu_first) {
                    case 1: // Jurusan
                        System.out.println("Pilih submenu:\n1. Input View Jurusan\n2. View Jurusan\n3. Delete Jurusan\nPilih Menu (1-3): ");
                        sub_menu = Integer.parseInt(sc.nextLine());
                        switch (sub_menu) {
                            case 1:
                                System.out.println("Masukkan Kode Jurusan: ");
                                String kode = sc.nextLine();
                                System.out.println("Masukkan Nama Jurusan: ");
                                String nama = sc.nextLine();
                                Jurusan inputJurusan = new Jurusan(kode, nama);
                                result = JurusanRepository.InputJurusan(inputJurusan);
                                System.out.println(result);
                                break;
                            case 2:
                                JurusanRepository.ViewJurusan();
                                break;
                            case 3:
                                result = JurusanRepository.DeleteJurusan();
                                System.out.println(result);
                                break;
                        }
                        break;

                    case 2: // Mata Kuliah
                        System.out.println("Pilih submenu:\n1. Input New Mata Kuliah\n2. Delete Mata Kuliah\n3. Input Mata Kuliah To Jurusan\nPilih Menu (1-3): ");
                        sub_menu = Integer.parseInt(sc.nextLine());
                        switch (sub_menu) {
                            case 1:
                                System.out.println("Masukkan Kode Mata Kuliah: ");
                                String kode = sc.nextLine();
                                System.out.println("Masukkan Nama Mata Kuliah: ");
                                String nama = sc.nextLine();
                                System.out.println("Masukkan Jumlah SKS: ");
                                int sks = Integer.parseInt(sc.nextLine());
                                MataKuliah inputMataKuliah = new MataKuliah(kode, nama, sks);
                                result = MataKuliahRepository.InputJurusan(inputMataKuliah);
                                System.out.println(result);
                                break;
                            case 2:
                                result = MataKuliahRepository.DeleteMataKuliah();
                                System.out.println(result);
                                break;
                            case 3:
                                result = MataKuliahRepository.RelationMataKuliahJurusan();
                                System.out.println(result);
                                break;
                        }
                        break;

                    case 3: // Mahasiswa
                        System.out.println("Pilih submenu:\n1. Input New Mahasiwa\n2. View mahasiswa\n3. View Detail Mahasiswa\nPilih Menu (1-3): ");
                        sub_menu = Integer.parseInt(sc.nextLine());
                        switch (sub_menu) {
                            case 1:
                                System.out.println("Masukkan nama mahasiswa: ");
                                String namaMhs = sc.nextLine();
                                System.out.println("Masukkan NIM mahasiswa: ");
                                String nimMhs = sc.nextLine();
                                JurusanRepository.ViewJurusan();
                                System.out.println("Masukkan Kode Jurusan mahasiswa: ");
                                String jurusan = sc.nextLine();
                                result = MahasiswaRepository.InputMahasiswa(namaMhs, nimMhs, jurusan);
                                System.out.println(result);
                                break;
                            case 2:
                                MahasiswaRepository.ViewListMahasiswa();
                                break;
                            case 3:
                                System.out.println("Masukkan NIM mahasiswa yang akan dicari: ");
                                String find_nim = sc.nextLine();
                                MahasiswaRepository.ViewDetailtMahasiswa(find_nim);
                                break;
                        }

                        break;
                }
            }
            else if (menu_first == 4) {
                System.out.println("Masukkan nim mahasiswa: ");
                String input_nama = sc.nextLine();
                MataKuliahRepository.ViewMataKuliah();
                System.out.println("Masukkan matakuliah yang diambil: ");
                String input_matkul = sc.nextLine();
                System.out.println("Masukkan nilai: ");
                int input_nilai = Integer.parseInt(sc.nextLine());
                String result = EvaluateRepository.InputNilai(input_nama, input_matkul, input_nilai);
                System.out.println(result);
            }
            else if (menu_first == 5) {
                System.out.println("Masukkan nim mahasiswa yang akan di cek: ");
                String input_nim = sc.nextLine();
                String result = EvaluateRepository.CountIP(input_nim);
                System.out.println(result);
            }
            else {
                break;
            }
        } while (true);
        System.out.println("Thank You");
    }
}
