/*
 * This source file was generated by the Gradle 'init' task
 */
package minggu9;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

public class App {

    class TextBox extends JPanel {
        
    }

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        String appName = "Simple Swing App";
        int width = 600;
        int height = 400;

        JFrame frame = new JFrame(appName);

        // Set Properties
        // Layout or position your components as needed before this
        // Email
        // Label
        JLabel label = new JLabel("Email");
        label.setBounds(100, 50, 200, 20);
        frame.add(label);
        // Text
        JTextField textField = new JTextField(15);
        textField.setBounds(100, 70, 200, 30);
        frame.add(textField);

        // Password
        // Label
        JLabel label2 = new JLabel("Password");
        label2.setBounds(100, 110, 200, 20);
        frame.add(label2);
        // Text
        JPasswordField passwordField = new JPasswordField(15);
        passwordField.setBounds(100, 130, 200, 30);
        frame.add(passwordField);

        

        //Button
        JButton btn = new JButton("Login");
        btn.setBounds(140, 180, 100, 40);
        frame.add(btn);

        //
        frame.setLayout(null);
        frame.setSize(width, height);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);

    }
}
